/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated', 
  //     dirName: '.'
  //   }
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
  docs: [
    {
      type: 'category',
      label: 'Big O Notation',
      link: {
        type: 'generated-index',
      },
      // collapsed: true,
      items: [
        'big-o/a-big-o-intro',
        'big-o/b-big-o-ds',
        'big-o/c-big-o-algo',
      ],
    },
    {
      type: 'category',
      label: 'Data Structures',
      link: {
        type: 'generated-index',
      },
      // collapsed: true,
      items: [
        'data-structures/a-arrays',
        'data-structures/b-strings',  
        'data-structures/c-linked-lists',
        'data-structures/d-hash-tables',
        'data-structures/e-hash-sets',
        'data-structures/f-stacks',
        'data-structures/g-queues',
        'data-structures/h-heaps',
        'data-structures/i-binary-search-trees',
        'data-structures/j-binary-trees',
        'data-structures/k-graphs',
        'data-structures/l-tries',
      ],
    },
    {
      type: 'category',
      label: 'Algorithms',
      link: {
        type: 'generated-index',
      },
      // collapsed: true,
      items: [
        'algorithms/a-binary-search',
        'algorithms/b-cyclic-sort',
        'algorithms/c-recursion',
        'algorithms/d-backtracking',
        'algorithms/e-greedy',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      link: {
        type: 'generated-index',
      },
      // collapsed: true,
      items: [
        'patterns/a-sliding-window',
        'patterns/b-two-pointers',
        'patterns/c-fast-and-slow-pointers',
        'patterns/d-intervals',
        'patterns/e-linked-list-reversal',
        'patterns/f-subsets',
        'patterns/g-topological-sorting',
        'patterns/h-bit-manipulation',
        'patterns/i-dp',
        'patterns/j-matrices',
        'patterns/k-math',
        'patterns/l-geometry',
      ],
    },
    {
      type: 'category',
      label: 'Primer Series',
      link: {
        type: 'generated-index',
      },
      // collapsed: true,
      items: [
        {
          type: 'category',
          label: 'A Primer on Java',
          link: {
            type: 'doc',
            id: 'primers/a-java-primer/java-primer-intro',
          },
        // collapsed: true,
          items: [
            'primers/a-java-primer/a-java-data-types',
            'primers/a-java-primer/b-java-concepts',
            'primers/a-java-primer/c-java-code-templates',
          ],
        },    
        {
          type: 'category',
          label: 'A Primer on Python',
          link: {
            type: 'doc',
            id: 'primers/b-python-primer/python-primer-intro',
          },
        // collapsed: true,
          items: [
            'primers/b-python-primer/a-python-data-types',
            'primers/b-python-primer/b-python-concepts',
            'primers/b-python-primer/c-python-code-templates',
          ],
        },    
        {
          type: 'category',
          label: 'A Primer on JS',
          link: {
            type: 'doc',
            id: 'primers/c-js-primer/js-primer-intro',
          },
        // collapsed: true,
          items: [
            'primers/c-js-primer/a-js-data-types',
            'primers/c-js-primer/b-js-concepts',
            'primers/c-js-primer/c-js-code-templates',
          ],
        },    
        {
          type: 'category',
          label: 'A Primer on TypeScript',
          link: {
            type: 'doc',
            id: 'primers/d-typescript-primer/typescript-primer-intro',
          },
        // collapsed: true,
          items: [
            'primers/d-typescript-primer/a-typescript-data-types',
            'primers/d-typescript-primer/b-typescript-concepts',
            'primers/d-typescript-primer/c-typescript-code-templates',
          ],
        },    
        'primers/regex-primer',
      ],
    },
    'solved-problems',
  ],
  // api: [
  //   '<path-if-not-curren-dir/doc-name>',
  //   '<path-if-not-curren-dir/doc-name>',
  //   '<path-if-not-curren-dir/doc-name>',
  //   {
  //     type: 'autogenerated',
  //     dirName: 'api',
  //   },
  // ],
};    
module.exports = sidebars;
    