/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Data Structures and Algorithms",
  "tagline": "A Very Practical Approach to Developing Problem Solving Skills",
  "url": "https://dbasusarkar.github.io",
  "baseUrl": "/dsa/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "dbasusarkar",
  "projectName": "dsa",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "sidebarPath": "/Users/Debajyoti/Wölkli-PRO/My Cloud Stuff/Computing/My GitHub Stuff/intro-to-dsa/dsabydbasusarkar/sidebars.js"
        },
        "blog": {
          "showReadingTime": false
        },
        "theme": {
          "customCss": "/Users/Debajyoti/Wölkli-PRO/My Cloud Stuff/Computing/My GitHub Stuff/intro-to-dsa/dsabydbasusarkar/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "plugins": [
    "@docusaurus/theme-live-codeblock"
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "python"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    },
    "navbar": {
      "title": "Data Structures and Algorithms",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/favicon.ico"
      },
      "items": [
        {
          "to": "/docs/category/big-o-notation",
          "label": "Big O",
          "position": "left"
        },
        {
          "to": "/docs/category/data-structures",
          "label": "DS",
          "position": "left"
        },
        {
          "to": "/docs/category/algorithms",
          "label": "Algorithms",
          "position": "left"
        },
        {
          "to": "/docs/category/patterns",
          "label": "Patterns",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "href": "https://github.com/dbasusarkar",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Internal Links",
          "items": [
            {
              "label": "Big O",
              "to": "/docs/category/big-o-notation"
            },
            {
              "label": "Data Structures",
              "to": "/docs/category/data-structures"
            },
            {
              "label": "Algorithms",
              "to": "/docs/category/algorithms"
            },
            {
              "label": "Patterns",
              "to": "/docs/category/patterns"
            },
            {
              "label": "Blog",
              "to": "/blog"
            }
          ]
        },
        {
          "title": "Links",
          "items": [
            {
              "label": "Personal Website",
              "href": "https://dbasusarkar.github.io"
            },
            {
              "label": "PGP/GPG Public Key",
              "href": "https://dbasusarkar.github.io/cheatsheets-tutorials-and-all-that-github/cheatsheets-tutorials-and-all-that-files/publickey.sci.comp@pm.me.asc"
            },
            {
              "label": "Keybase Public Profile",
              "href": "https://keybase.io/dbasusarkar"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Cheatsheets, Tutorials, & All That",
              "href": "https://dbasusarkar.github.io/cheatsheets-tutorials-and-all-that-github/cheatsheets-tutorials-and-all-that.html"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/dbasusarkar"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Debajyoti Basu Sarkar. Built with Docusaurus."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
